<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'mokka\\method' => '/method/Method.php',
                'mokka\\mock' => '/mock/Mock.php',
                'mokka\\mockedmethod' => '/method/MockedMethod.php',
                'mokka\\mockinterface' => '/mock/MockInterface.php',
                'mokka\\mokka' => '/Mokka.php',
                'mokka\\stubbedmethod' => '/method/StubbedMethod.php',
                'mokka\\token' => '/Token.php',
                'mokka\\verificationexception' => '/VerificationException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
